---
title: "In-class Exercise 2"
description: |
  In this hands-on exercise, I learnt how to handle geospatial data in R by using sf package
author:
  - name: Darryl Kwok
    url: https://example.com/darrylkwok
date: 08-23-2021
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Getting Started 

This code chunk performs three tasks:

- create and install a list of R packages needed

```{r echo=TRUE, eval=TRUE}

packages <- c('sf', 'tidyverse')
for(p in packages) {
  if(!require(p, character.only = T)) {
    install.packages(p)
  }
  library(p, character.only = T)
}
```

```{r}
mpsz = st_read(dsn = "data/geospatial", layer = "MP14_SUBZONE_WEB_PL")
cyclingpath = st_read(dsn="data/geospatial", layer = "CyclingPath")
preschool = st_read("data/geospatial/pre-schools-location-kml.kml")

st_geometry(mpsz)
st_geometry(cyclingpath)
st_geometry(preschool)

glimpse(mpsz)
head(mpsz, n=5)
plot(mpsz)
plot(st_geometry(mpsz))
plot(mpsz["PLN_AREA_N"])
plot(mpsz["REGION_N"])
st_crs(mpsz)

mpsz3414 <- st_set_crs(mpsz, 3414)
st_crs(mpsz3414)

preschool3414 <- st_transform(preschool, 
                              crs = 3414)
st_geometry(preschool3414)

listings <- read_csv("data/aspatial/listings.csv")
glimpse(listings)

listings_sf <- st_as_sf(listings, 
                       coords = c("longitude", "latitude"),
                       crs=4326) %>%
  st_transform(crs = 3414)

glimpse(listings_sf)

buffer_cycling <- st_buffer(cyclingpath, 
                               dist=5, nQuadSegs = 30)
buffer_cycling$AREA <- st_area(buffer_cycling)
sum(buffer_cycling$AREA)

mpsz3414$`PreSch Count`<- lengths(st_intersects(mpsz3414, preschool3414))

summary(mpsz3414$`PreSch Count`)
top_n(mpsz3414, 1, `PreSch Count`)

mpsz3414$Area <- mpsz3414 %>%
  st_area()

mpsz3414 <- mpsz3414 %>%
  mutate(`PreSch Density` = `PreSch Count`/Area * 1000000)

hist(mpsz3414$`PreSch Density`)

ggplot(data=mpsz3414, 
       aes(x= as.numeric(`PreSch Density`))) +
  geom_histogram(bins=20, 
                 color="black", 
                 fill="light blue") +
  labs(title = "Are pre-school even distributed in Singapore?",
       subtitle= "There are many planning sub-zones with a single pre-school, on the other hand, \nthere are two planning sub-zones with at least 20 pre-schools",
      x = "Pre-school density (per km sq)",
      y = "Frequency")
```








